# config.py

NANO_SECONDS = 1
MICRO_SECONDS = 1000 * NANO_SECONDS
MILLI_SECONDS = 1000 * MICRO_SECONDS
SECONDS = 1000 * MILLI_SECONDS

MINE_RATE = 4 * SECONDS

STARTING_BALANCE = 1000

MINING_REWARD = 50
MINING_REWARD_INPUT = {'address': '*--official-mining-reward--*'}
