const API_BASE_URL = 'http://localhost:5000';

const NANO_SECONDS_PY = 1;
const MICRO_SECONDS_PY = 1000 * NANO_SECONDS_PY;
const MILLI_SECONDS_PY = 1000 * MICRO_SECONDS_PY;

const MILLI_SECONDS_JS = 1;
const SECONDS_JS = 1000 * MILLI_SECONDS_JS;

export {API_BASE_URL, MILLI_SECONDS_PY, SECONDS_JS};
