const API_BASE_URL = 'http://localhost:5000';

const NANO_SECONDS_PY = 1;
const MICRO_SECONDS_PY = 1000 * NANO_SECONDS_PY;
const MILLI_SECONDS_PY = 1000 * MICRO_SECONDS_PY;

export {API_BASE_URL, MILLI_SECONDS_PY};
