
class TransactionPool:
    def __init__(self):
        self.transaction_map = {}

    def set_transaction(self, trans):
        ''' Set a transaction in the transaction pool '''
        self.transaction_map[trans.id] = trans

    def existing_transaction(self, address):
        '''
            Find a transaction generated by the address in the transaction pool.
        '''
        for trans in self.transaction_map.values():
            if trans.input['address'] == address:
                return trans
